export const deDE = {
    levelCompleted: "Level abgeschlossen!",
    close: "Schließen",
    goBack: "Zurück",
    boardSize: "Spielfeldgröße",
    theme: "Design",
    on: "An",
    off: "Aus",
    experimentalInput: "Experimentelle Eingabe (Zeichenmodus)",
    settingsSaved: "Einstellungen werden automatisch gespeichert. Die Spielfeldgröße wird erst im nächsten Level angewendet. Beende dein aktuelles Level oder klicke auf „Neues Level“, um die Spielfeldgröße zu ändern.",
    amoledNotice: "Das dunkle AMOLED-Design reduziert den Akkuverbrauch, indem schwarze Hintergrundfarben verwendet werden, wodurch einige Pixel des Displays physisch deaktiviert werden. Bei herkömmlichen LCD-Displays hat das AMOLED-Design kaum Einfluss auf den Akkuverbrauch, da selbst schwarze Pixel beleuchtet sind.",
    howToPlay: "Wie spielt man?",
    rule1: "Platziere Königinnen so auf dem Spielfeld, dass jede Reihe, jede Spalte und jede Farbregion genau eine Königin enthält.",
    rule2: "Du kannst Kreuze als Notizen setzen, um Stellen zu markieren, an denen keine Königin platziert werden kann. Dies hat keinen Einfluss auf das Spiel.",
    rule3: "Königinnen dürfen sich NICHT berühren, auch nicht diagonal.",
    rule4: "Jede Reihe und jede Spalte darf nicht mehr als eine Königin enthalten.",
    rule5: "Jede Farbregion darf nicht mehr als eine Königin enthalten.",
    rule1alt: "Korrekte Lösung",
    rule2alt: "Kreuze",
    rule3alt: "Diagonale Berührung",
    rule4alt: "Reihe/Spalte enthält mehrere Königinnen",
    rule5alt: "Farbregion enthält mehrere Königinnen",
    settings: "Einstellungen",
    appName: "Queens",
    clearBoard: "Spielfeld leeren",
    hint: "Hinweis",
    newLevel: "Neues Level",
    rules: "Regeln",
    themeDark: "Dunkel",
    themeGreen: "Grün",
    themeBlue: "Blau",
    themeRed: "Rot",
    themeDarkAmoled: "Dunkel (AMOLED)",
    themeLight: "Hell",
    language: "Sprache",
}
