export const enUS = {
    levelCompleted: "Level completed!",
    close: "Close",
    goBack: "Go Back",
    boardSize: "Board Size",
    theme: "Theme",
    on: "On",
    off: "Off",
    experimentalInput: "Experimental input (draw mode)",
    settingsSaved: "Settings are saved automatically. Board size setting applies to your next level. Finish your current level or click \"New level\" to change board size.",
    amoledNotice: "Dark AMOLED theme reduces battery usage by using black background colors which physically disables some of pixels on your display. On regular LCD displays AMOLED theme almost takes no effect on battery usage because even black pixels are highlighted.",
    howToPlay: "How to play?",
    rule1: "Place queens on the board so each row, column and color region contains exactly one queen.",
    rule2: "You can make notes using crosses like where a queen cannot be placed. It does not affect gameplay.",
    rule3: "Queens MUST NOT touch each other even diagonally.",
    rule4: "Each row and colum must not have multiple queens.",
    rule5: "Each color region must not have multiple queens.",
    rule1alt: "Correct answer",
    rule2alt: "Crosses",
    rule3alt: "Diagonal touch",
    rule4alt: "Row/Column contains multiple queens",
    rule5alt: "Color region contains multiple queens",
    settings: "Settings",
    appName: "Queens",
    clearBoard: "Clear board",
    hint: "Hint",
    newLevel: "New level",
    rules: "Rules",
    themeDark: "Dark",
    themeGreen: "Green",
    themeBlue: "Blue",
    themeRed: "Red",
    themeDarkAmoled: "Dark (amoled)",
    themeLight: "Light",
    language: "Language",
}
